name: CI
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        spec:
        - { scheme: 'GT', config: 'Release', sdk: 'macosx', destination: 'generic/platform=macOS'}

    steps:
        - uses: actions/checkout@v3

        - uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: '14.2'

        - name: Setup Keychain
          run: |
            echo "${{ secrets.APPLE_DEVELOPMENT_P12 }}" | base64 --decode > ./development.p12
            echo "${{ secrets.APPLE_DEVELOPMENT_P12_PASSWORD }}" | base64 --decode > ./development.pass
            PASS=$(cat ./development.pass | base64 --decode)
            security create-keychain -p paswsword build.keychain
            security default-keychain -s build.keychain
            security unlock-keychain -p paswsword build.keychain
            security import ./development.p12 -k build.keychain -P ${PASS} -T "/usr/bin/codesign"
            security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k password build.keychain

        - name: ${{ matrix.spec.scheme }} Build
          env:
            SCHEME: ${{ matrix.spec.scheme }}
            CONFIG: ${{ matrix.spec.config }}
            SDK: ${{ matrix.spec.sdk }}
            DESTINATION: ${{ matrix.spec.destination }}
          run: |
            xcodebuild build -configuration ${CONFIG} -scheme ${SCHEME} ${ARCH_FLAGS} -sdk ${SDK} -destination ${DESTINATION} 

        - name: Remove Keychain
          if: always()
          run: |
            security default-keychain -s "login.keychain"
            security delete-keychain build.keychain
